name: vmpa
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.2
  # curved_navigation_bar: ^1.0.3
  get: ^4.6.6
  intl: ^0.18.1
  file_picker: ^5.5.0
  # open_file: ^3.3.2
  form_field_validator: ^1.1.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  loading_animation_widget: ^1.2.0+4
  firebase_storage: ^11.2.7
  cached_network_image: ^3.3.0
  # internet_connection_checker: ^1.0.0+1
  just_audio: ^0.9.35
  just_audio_background: ^0.0.1-beta.10
  # email_auth: ^1.0.0
  # pin_code_fields: ^8.0.1
  flutter_slidable: ^3.0.0
  lottie: ^2.6.0
  uuid: ^4.1.0
  path_provider: ^2.1.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: "ic_launcher"
  adaptive_icon_background: "assets/images/icon/vmpa_icon.png"
  ios: true
  image_path: "assets/images/icon/vmpa_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # flutter pub run flutter_launcher_icons

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/jpg/
    - assets/images/icon/
    - assets/Animation/
